services:
  backend:
    container_name: api
    image: zatarain/bookshop-api
    build: .
    ports:
      - 3000:3000
    volumes:
      - database:/data

volumes:
  database:
    name: bookshop-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: data
