name: Continuous Integration Pipeline
on:
  push:
    branches: [main, staging, development]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Installing go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      - name: Installing dependencies
        run: go mod tidy
      - name: Run linter
        run: go mod tidy && gofmt -l .
      - name: Run test cases
        run: go test -v --cover
              
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'main' }}
          tags: ${{ github.repository }}:latest
